class Helpers:
    social_domains = {
        # Major platforms
        "facebook.com",
        "fb.com",
        "fb.me",
        "twitter.com",
        "x.com",
        "t.co",
        "linkedin.com",
        "lnkd.in",
        "instagram.com",
        "instagr.am",
        "youtube.com",
        "youtu.be",
        "tiktok.com",
        # Professional networks
        "xing.com",
        "angellist.com",
        "crunchbase.com",
        "glassdoor.com",
        # Messaging platforms
        "whatsapp.com",
        "wa.me",
        "telegram.org",
        "telegram.me",
        "t.me",
        "discord.com",
        "discord.gg",
        "slack.com",
        "skype.com",
        "viber.com",
        "signal.org",
        "wechat.com",
        "weixin.qq.com",
        "line.me",
        # Content platforms
        "pinterest.com",
        "pin.it",
        "reddit.com",
        "redd.it",
        "tumblr.com",
        "medium.com",
        "quora.com",
        "vimeo.com",
        "dailymotion.com",
        "twitch.tv",
        "soundcloud.com",
        "spotify.com",
        "apple.com/music",
        "deezer.com",
        "bandcamp.com",
        # Visual platforms
        "flickr.com",
        "flic.kr",
        "behance.net",
        "dribbble.com",
        "deviantart.com",
        "500px.com",
        "unsplash.com",
        "vsco.co",
        # Asian platforms
        "weibo.com",
        "weibo.cn",
        "douyin.com",
        "bilibili.com",
        "zhihu.com",
        "xiaohongshu.com",
        "kuaishou.com",
        "qq.com",
        "kakao.com",
        "naver.com",
        "daum.net",
        # Russian/Eastern European platforms
        "vk.com",
        "vkontakte.ru",
        "ok.ru",
        "odnoklassniki.ru",
        "my.mail.ru",
        "yandex.ru",
        # Professional/Developer platforms
        "github.com",
        "gitlab.com",
        "bitbucket.org",
        "stackoverflow.com",
        "codepen.io",
        "kaggle.com",
        "hackerrank.com",
        "leetcode.com",
        # Review platforms
        "yelp.com",
        "tripadvisor.com",
        "trustpilot.com",
        "g2.com",
        "capterra.com",
        # Other platforms
        "snapchat.com",
        "clubhouse.com",
        "mastodon.social",
        "threads.net",
        "bluesky.social",
        "meetup.com",
        "houzz.com",
    }

    social_patterns = [
        r"/social[s]?/",
        r"/share/",
        r"/follow/",
        r"/connect/",
        r"/@[\w]+",
        r"/u/[\w]+",
        r"/user/[\w]+",
        r"/profile/",
        r"/company/",
        r"/c/[\w]+",
        r"/channel/",
    ]

    phone_patterns = [
        r"[\+]?[(]?[0-9]{1,3}[)]?[-\s\.]?[(]?[0-9]{1,4}[)]?[-\s\.]?[0-9]{1,4}[-\s\.]?[0-9]{1,9}",
        r"[\+]?[0-9]{1,3}[-\s]?[0-9]{2,4}[-\s]?[0-9]{3,4}[-\s]?[0-9]{3,4}",
        r"[(]?[0-9]{3}[)]?[-\s]?[0-9]{3}[-\s]?[0-9]{4}",
        r"[0-9]{10,15}",
    ]

    email_pattern = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"

    name_selectors = [
        ".exhibitor__bar-name",
        ".exhibitor__name",
        "h1",
        "h2",
        "h3",
        ".company-name",
        ".company-title",
        ".exhibitor-name",
        ".brand-name",
        ".business-name",
        ".vendor-name",
        '[class*="company-name"]',
        '[class*="company_name"]',
        '[class*="business-name"]',
        '[class*="business_name"]',
        '[class*="title"]',
        '[class*="heading"]',
        '[itemprop="name"]',
        '[property="og:title"]',
        ".profile-name",
        ".org-name",
        ".merchant-name",
        "#company-name",
        "#business-name",
    ]

    logo_selectors = [
        'img[alt*="logo" i]',
        'img[src*="logo" i]',
        ".logo img",
        ".company-logo img",
        ".brand-logo img",
        ".logo-container img",
        ".logo-wrapper img",
        '[class*="logo"] img',
        '[id*="logo"] img',
        ".header img",
        ".branding img",
        'img[class*="logo"]',
        'img[id*="logo"]',
        ".company-image img",
        ".vendor-image img",
        ".profile-image img",
        ".avatar img",
        '[itemprop="logo"]',
        '[property="og:image"]',
    ]

    description_selectors = [
        ".description",
        ".company-description",
        ".about",
        ".company-about",
        ".company-info",
        ".bio",
        ".overview",
        ".summary",
        ".profile-description",
        '[class*="description"]',
        '[class*="about"]',
        '[class*="overview"]',
        '[class*="summary"]',
        '[itemprop="description"]',
        'meta[name="description"]',
        ".company-details p",
        ".vendor-details p",
        "p.description",
        "div.description p",
        ".content p:first-of-type",
        "article p:first-of-type",
    ]



    phone_selectors = [
        'a[href^="tel:"]',
        '[href^="tel:"]',
        ".phone",
        ".telephone",
        ".phone-number",
        ".contact-phone",
        ".business-phone",
        '[class*="phone"]',
        '[class*="telephone"]',
        '[itemprop="telephone"]',
        '[property="og:phone_number"]',
        ".tel",
        ".mobile",
        ".cell",
        '[class*="tel"]',
        '[class*="mobile"]',
        "span.phone",
        "div.phone",
        "p.phone",
        ".contact-info .phone",
        ".contact-details .phone",
        "[data-phone]",
        "[data-telephone]",
    ]

    contact_selectors = [
        ".contact",
        ".contact-info",
        ".contact-details",
        ".contact-us",
        ".get-in-touch",
        '[class*="contact"]',
        '[id*="contact"]',
    ]

    email_selectors = [
        'a[href^="mailto:"]',
        '[href^="mailto:"]',
        ".email",
        ".email-address",
        ".contact-email",
        ".business-email",
        ".company-email",
        '[class*="email"]',
        '[class*="e-mail"]',
        '[itemprop="email"]',
        '[property="og:email"]',
        "span.email",
        "div.email",
        "p.email",
        ".contact-info .email",
        ".contact-details .email",
        "[data-email]",
        '[type="email"]',
    ]

    contact_selectors = [
        ".contact",
        ".contact-info",
        ".contact-details",
        ".footer",
        ".contact-us",
        '[class*="contact"]',
        '[id*="contact"]',
    ]

    website_selectors = [
        'a[href*="www."]',
        'a[href*="http"]',
        'a:has-text("website")',
        'a:has-text("visit")',
        ".website a",
        ".company-website a",
        ".official-website a",
        ".web-link a",
        '[class*="website"] a',
        '[class*="web-link"] a',
        "a.website",
        "a.url",
        "a.link",
        '[itemprop="url"]',
        '[property="og:url"]',
    ]

    social_container_selectors = [
        ".social-links",
        ".social-media",
        ".socials",
        ".follow-us",
        ".connect",
        ".social-icons",
        '[class*="social"]',
        '[class*="follow"]',
        ".footer",
        ".contact-info",
        ".sidebar",
        "aside",
        "footer",
        ".share-buttons",
    ]

    company_selectors = [
        # Generic company selectors
        'a[href*="company"]',
        'a[href*="exhibitor"]',
        'a[href*="vendor"]',
        'a[href*="supplier"]',
        'a[href*="manufacturer"]',
        'a[href*="partner"]',
        'a[href*="member"]',
        'a[href*="profile"]',
        'a[href*="business"]',
        'a[href*="merchant"]',
        # Class-based selectors
        ".company-item a",
        ".exhibitor-item a",
        ".vendor-item a",
        ".supplier-item a",
        ".company-card a",
        ".exhibitor-card a",
        ".business-card a",
        ".merchant-card a",
        ".list-item a",
        ".grid-item a",
        ".result-item a",
        ".listing-item a",
        # ID and class patterns
        '[class*="company"] a',
        '[class*="exhibitor"] a',
        '[class*="vendor"] a',
        '[class*="listing"] a',
        '[class*="item"] a',
        '[class*="card"] a',
        # Data attributes
        "[data-company] a",
        "[data-exhibitor] a",
        "[data-vendor] a",
        "[data-item] a",
        # Common list structures
        "ul li a",
        "ol li a",
        ".results a",
        ".listings a",
        "article a",
        ".post a",
        # Table structures
        "table tbody tr a",
        "table tr td a",
    ]

    skip_patterns = [
        "login",
        "register",
        "signup",
        "signin",
        "contact",
        "about",
        "privacy",
        "terms",
        "cookie",
        "help",
        "faq",
        "blog",
        "news",
        "events",
        "home",
        "#",
        "javascript:",
        "mailto:",
        "tel:",
        ".pdf",
        ".doc",
        ".xls",
        ".ppt",
        "facebook",
        "twitter",
        "linkedin",
        "instagram",
        "youtube",
        "tiktok",
    ]

    detail_patterns = [
        "/company/",
        "/exhibitor/",
        "/vendor/",
        "/profile/",
        "/supplier/",
        "/member/",
        "/business/",
        "/merchant/",
        "/detail/",
        "/view/",
        "/show/",
        r"/\d+",  # URLs with IDs
    ]

    item_selectors = [
        ".item",
        ".card",
        ".listing",
        '[class*="item"]',
        '[class*="card"]',
        "article",
        ".result",
        ".entry",
    ]

    scroll_methods = [
        "window.scrollTo(0, document.body.scrollHeight)",
        "window.scrollBy(0, window.innerHeight * 3)",
        "document.documentElement.scrollTop = document.documentElement.scrollHeight",
    ]

    load_more_selectors = [
        'button:has-text("load more")',
        'button:has-text("show more")',
        'button:has-text("view more")',
        'a:has-text("load more")',
        'a:has-text("show more")',
        '[class*="load-more"]',
        '[class*="show-more"]',
        ".pagination-next",
        ".next-page",
    ]


helpers = Helpers()
